# ORDER BY Challenges

\*\*Use SAMPLEDB Database\*\*

In [1]:
USE SAMPLEDB
GO

### **First Challenge**  

Challenge: Write a query that returns all employees ordered alphabetically by their last name from A to Z.

In [2]:
SELECT * FROM hcm.employees
ORDER BY last_name ASC;

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
166,Sundar,NULL,Ande,9,153600.00,1995-06-12,2014-06-21,80,147,011.069.6306,9923 Dinorben St #4838,Childs Hill Ward,NULL,NW11 8DY,27
130,Mark,Jeffrey,Atkinson,13,67200.00,1979-02-04,2010-02-25,50,121,650.447.4686,94307 Annamark Junction,Seattle,Washington,98104,28
202,Patrick,Ronan,Bacon,17,144000.00,1993-11-10,2013-11-04,NULL,201,603.241.7070,92 South St,Alligator Creek,Queensland,4740,2
204,Richard,Michael,Baer,19,240000.00,1961-04-07,2015-04-16,NULL,101,515.241.7574,5210 E Airy St #2,Brandy Creek,Queensland,4800,2
116,Shelli,NULL,Baida,11,69600.00,1959-01-23,2016-01-10,30,114,515.513.4164,05 School Lane,Seattle,Washington,98121,28
167,Amit,Tom,Banda,9,148800.00,1978-05-09,2017-05-28,80,147,011.910.9493,7643 Campbell St,Penge and Cator Ward,NULL,BR3 1LT,27
172,Edward,Neil,Bates,9,175200.00,1968-02-04,2014-02-09,80,148,011.649.3798,7901 Beech St,St. Helier Ward,NULL,SM4 5PY,27
192,Sarah,Maisie,Bell,14,96000.00,1969-04-05,2013-04-22,NULL,123,650.950.5406,5399 Mcwhorter Rd,Calala,New South Wales,2340,2
100,Jack,John,Bernard,1,576000.00,1994-01-13,2017-01-23,90,NULL,515.996.5357,3 Kenwood Plaza,Seattle,Washington,98185,28
151,David,NULL,Bernstein,9,228000.00,1963-04-07,2017-04-13,80,145,011.474.4371,5344 Bengel St #5,Millwall Ward,NULL,E14 5DR,27
129,Laura,Tanya,Bissot,13,79200.00,1987-04-02,2016-04-08,50,121,650.824.8471,5378 Porter Place,Seattle,Washington,98195,28
169,Alexander,Joseph,Bloom,9,240000.00,1964-09-23,2014-09-23,80,148,011.733.4576,7 Netley St,Custom House Ward,NULL,E16 3DP,27
185,Alexis,NULL,Bull,14,98400.00,1963-03-26,2013-03-26,NULL,121,650.315.7253,6452 Pilgrim St #5,Seven Sisters Ward,NULL,N15 6TH,27
187,Anthony,Alec,Cabrio,14,72000.00,1980-12-18,2014-12-08,NULL,121,650.107.6163,9166 Devon St #905,Knightsbridge and Belgravia Wa,NULL,SW1W 8JY,27
154,Raewyn,Phoebe,Cambrault,9,180000.00,1985-10-25,2010-10-05,80,145,011.903.1413,76 Dawber St #6,Blackheath Westcombe Ward,NULL,SE3 7JY,27
148,Gerald,NULL,Cambrault,8,264000.00,1973-06-27,2013-06-26,80,100,011.869.8196,61 Miriam St,Abbey Road Ward,NULL,NW8 9BD,27
105,Paul,James,Cameron,15,115200.00,1985-12-20,2018-12-14,60,103,590.826.7764,3 Calypso Parkway,Seattle,Washington,98133,28
107,Maria,April,Cameron,15,100800.00,1973-03-11,2008-03-01,60,103,590.643.5171,578 Brentwood Parkway,Seattle,Washington,98140,28
112,Lena,Michelle,Chadwick,5,187200.00,1957-02-03,2004-02-04,100,108,515.390.5375,6 Argyle Rd,Sydney,New South Wales,2300,2
110,John,NULL,Chen,5,196800.00,1961-01-24,2007-01-06,100,108,515.003.1575,406 Eastern road,Sydney,New South Wales,2481,2
188,Kelly,Natalie,Chung,14,91200.00,1968-12-14,2009-12-07,NULL,122,650.825.3939,3 S Willow St #82,Bygalorie,New South Wales,2669,2
114,Diana,Mary,Colman,10,264000.00,1986-02-13,2013-02-20,30,100,515.776.5640,576 Nancy Alley,Seattle,Washington,98115,28
119,Karen,Rhonda,Colmenares,11,60000.00,1987-03-06,2006-03-04,30,114,515.593.3752,23 Kennedy Drive,Seattle,Washington,98166,28
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
186,Julia,Veronica,Dellinger,14,81600.00,1977-01-08,2005-01-06,NULL,121,650.297.2123,70 Lilly Rd,Shirley Ward,NULL,CR0 7PT,27
189,Jennifer,Hazel,Dilly,14,86400.00,1957-12-26,2018-12-20,NULL,122,650.517.8059,199 Maple Ave,Boolaroo,New South Wales,2284,2
160,Louise,Christina,Doran,9,180000.00,1971-01-25,2010-01-20,80,146,011.432.6996,5 Gainsborough Rd,Newington Ward,NULL,SE1 6EH,27
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
147,Alberto,Jesus,Errazuriz,8,288000.00,1973-08-17,2003-08-12,80,100,011.548.7376,62 Margaret St,Royal Hospital Ward,NULL,SW3 4ND,27
193,Britney,Josie,Everett,14,93600.00,1958-01-01,2011-01-10,NULL,123,650.830.8731,7 Hall St,Nambucca Heads,New South Wales,2448,2
197,Milford,NULL,Feeney,14,72000.00,1962-06-10,2010-06-26,NULL,124,650.523.2373,6 Hope Rd #10,Pinnacle,Queensland,4741,2
170,William,Nigel,Fox,9,230400.00,1992-07-13,2014-07-09,80,148,011.225.0992,2 Prince Rupert St,West Wickham Ward,NULL,BR3 6SX,27
190,Timothy,Mitchell,Gates,14,69600.00,1983-02-01,2018-02-08,NULL,122,650.340.2668,5 30w W #3083,Hillston,New South Wales,2675,2
183,Girard,Rafael,Geoni,14,67200.00,1965-08-02,2018-08-24,NULL,120,650.244.2292,2015 Suburban Rd,Springfield Ward,NULL,N16 6TD,27
206,William,Abe,Gietz,7,199200.00,1962-10-24,2016-10-16,NULL,205,515.598.9812,15126 Goldenwest St,Toowoomba South,Queensland,4350,2
199,Douglas,Robert,Grant,14,62400.00,1993-02-04,2016-02-25,NULL,124,650.742.9288,35673 Annapolis Rd #190,Ascot,Queensland,4359,2
178,Olivia,Chantelle,Grant,9,168000.00,1995-06-26,2013-06-05,NULL,149,011.486.1642,5 Bentinck St,Churchill Ward,NULL,SW1V 3EW,27
163,Danielle,Marie,Greene,9,228000.00,1990-05-16,2012-05-05,80,147,011.093.1450,6301 Dorset Rd,Harefield Ward,NULL,UB9 6LF,27
121,Jack,Earl,Hale,12,196800.00,1966-09-13,2011-09-07,50,100,650.083.4633,3951 Merrick Lane,Seattle,Washington,98133,28
152,Peter,NULL,Hall,9,216000.00,1994-05-11,2015-05-18,80,145,011.551.8183,227 Albert Terrace,Belvedere Ward,NULL,DA17 6EF,27
201,Michael,Timothy,Hartstein,16,312000.00,1965-07-11,2010-07-04,NULL,100,515.533.9401,423 S Navajo St #56,Brookhill,Queensland,4816,2
111,Llyod,Eric,Henderson,5,184800.00,1992-10-02,2016-10-07,100,108,515.689.5566,60 Highway Road,Sydney,New South Wales,2155,2
205,Shelley,NULL,Higgins,6,288192.00,1975-04-04,2015-04-10,NULL,101,515.509.9456,52347 San Fernando Rd,Coppabella,Queensland,4741,2
181,Laura,Caitlyn,Hobbs,14,74400.00,1977-10-07,2014-10-23,NULL,120,650.104.4982,2476 Marsh St,Markhouse Ward,NULL,E17 8NP,27
174,Annemarie,Olivia,Hoffman,9,264000.00,1975-08-04,2016-08-01,80,149,011.657.3709,231 Wordsworth St,Harrow Weald Ward,NULL,HA3 6TH,27
135,Mitch,Matthew,Holt,13,57600.00,1992-05-10,2012-05-23,50,122,650.500.8591,3 Muir Trail,Seattle,Washington,98104,28
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
175,Hiroko,NULL,Hutton,9,211200.00,1995-04-02,2018-04-27,80,149,011.181.1371,7252 Dansie St,East Finchley Ward,NULL,N2 9JL,27
203,Susan,Jane,Jacobs,18,156000.00,1985-07-11,2012-07-19,NULL,101,515.541.4415,4 Piccadilly Place,Manchester,NULL,M1 3BG,27
179,Richie,Hugh,Johnson,9,148800.00,1977-11-17,2010-11-20,NULL,149,011.823.8442,7 Canton St,Mildmay Ward,NULL,N1 4RF,27
195,Catrina,Hollie,Jones,14,67200.00,1957-02-17,2005-02-19,NULL,123,650.146.4730,28 Aaronwood Ave Ne,Coombell,New South Wales,2470,2
115,Alexander,NULL,Khoo,11,74400.00,1959-10-17,2011-10-04,30,114,515.125.0259,22270 Portage Park,Seattle,Washington,98104,28
106,Russell,John,King,15,115200.00,1989-04-18,2008-04-21,60,103,590.964.4035,5 Barnett Drive,Seattle,Washington,98148,28
156,Janette,Helen,King,9,240000.00,1989-09-28,2019-09-22,80,146,011.033.2021,3347 Lawrence Rd #456,Haverstock Ward,NULL,NW5 4EU,27
137,Renske,NULL,Ladwig,13,86400.00,1972-07-18,2006-07-15,50,123,650.960.5034,8 Upham Crossing,Seattle,Washington,98127,28
127,James,NULL,Landry,13,57600.00,1972-04-13,2011-04-11,50,120,650.816.0130,95 Elka Crossing,Seattle,Washington,98109,28
102,Judy,Georgia,Lawson,2,408000.00,1960-11-12,2010-11-26,90,100,515.195.9617,17 American Ash Trail,Seattle,Washington,98127,28
165,David,Craig,Lee,9,163200.00,1987-07-03,2010-07-13,80,147,011.322.6428,22 Kilshaw St,Wimbledon Park Ward,NULL,SW19 7DT,27
177,Theron,NULL,Livingston,9,201600.00,1988-08-20,2013-08-24,80,149,011.283.5306,1257 Stone St,Northwood Ward,NULL,HA6 1AN,27
133,Jason,Paul,Mallin,13,79200.00,1985-12-22,2016-12-06,50,122,650.315.4723,7975 Pleasure Crossing,Seattle,Washington,98166,28
128,Steven,Andrew,Markle,13,52800.00,1970-08-19,2004-08-01,50,120,650.058.3953,18499 Autumn Leaf Trail,Seattle,Washington,98185,28
131,James,Ian,Marlow,13,60000.00,1984-06-21,2013-06-09,50,121,650.860.2883,1891 Sage Court,Seattle,Washington,98109,28
164,Tamara,Madeleine,Marvins,9,172800.00,1963-09-14,2001-09-15,80,147,011.316.1849,11 Tetlow St,Parsons Green and Walham Ward,NULL,SW6 4QP,27
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28
194,Samuel,Christopher,McCain,14,76800.00,1985-06-27,2017-06-09,NULL,123,650.864.7855,5 W Allen St,Mccullys Gap,New South Wales,2333,2
158,Allan,Arthur,McEwen,9,216000.00,1966-07-13,2010-07-26,80,146,011.734.7834,588 Venmore St,Twickenham Riverside Ward,NULL,TW1 2QH,27
126,Irene,NULL,Mikkilineni,13,64800.00,1962-02-16,2001-02-22,50,120,650.810.3548,6 Veith Place,Seattle,Washington,98115,28
104,Rachel,Alison,Mortensen,15,144000.00,1959-07-27,2003-07-25,60,103,590.876.6936,27 Dunning Street,Seattle,Washington,98109,28
124,Kevin,NULL,Mourgos,12,139200.00,1970-09-03,2009-09-21,50,100,650.168.8824,52 Hollow Ridge Street,Seattle,Washington,98148,28
125,Julia,Aleisha,Nayer,13,76800.00,1972-09-16,2015-09-17,50,120,650.290.0080,7 Summerview Crossing,Seattle,Washington,98109,28
153,Christopher,NULL,Olsen,9,192000.00,1958-10-13,2007-10-12,80,145,011.628.3870,464 Back Nile St #618,Acton Central Ward,NULL,W3 6QJ,27
132,Gavin,Francis,Olson,13,52800.00,1973-02-16,2008-02-15,50,121,650.283.1659,9794 Carey Hill,Seattle,Washington,98109,28
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
168,Danny,NULL,Ozer,9,276000.00,1990-03-28,2014-03-04,80,148,011.597.1458,1779 Bird St,East Sheen Ward,NULL,SW14 8JZ,27
146,Karen,Courtney,Partners,8,336000.00,1986-12-06,2002-12-14,80,100,011.116.5962,41 Benedict St,Aldborough Ward,NULL,IG2 7QG,27
140,Mayank,NULL,Patel,13,60000.00,1983-06-16,2010-06-05,50,123,650.281.1672,2954 North Plaza,Seattle,Washington,98104,28
191,Chuck,NULL,Perkins,14,60000.00,1994-03-01,2015-03-20,NULL,122,650.749.2243,6940 Prospect Pl,Caldwell,New South Wales,2710,2
136,Hazel,Danielle,Philtanker,13,52800.00,1994-10-17,2017-10-13,50,122,650.908.2415,8 South Avenue,Seattle,Washington,98185,28
141,Trenna,Jasmine,Rajs,13,84000.00,1965-09-27,2006-09-19,50,124,650.295.9197,6896 Reindahl Parkway,Seattle,Washington,98115,28
101,Don,Fred,Reilly,2,408000.00,1966-12-27,2006-12-28,90,100,515.848.4385,61 Banding Street,Seattle,Washington,98166,28
134,Michael,Robert,Rogers,13,69600.00,1969-08-25,2018-08-22,50,122,650.763.3210,212 High Crossing Terrace,Seattle,Washington,98148,28
139,Tony,Sean,Rogers,13,64800.00,1976-02-21,2017-02-12,50,123,650.250.0801,89 Randy Junction,Seattle,Washington,98109,28
149,Michael,NULL,Rogers,8,252000.00,1970-10-19,2011-10-05,80,100,011.612.8871,5382 Redfern St,West End Ward,NULL,W1J 0QH,27
145,Harold,John,Russell,8,336000.00,1969-01-06,2004-01-15,80,100,011.781.2573,67 Micawber St,Brockley Ward,NULL,SE14 6RQ,27
184,Nandita,NULL,Sarchand,14,100800.00,1975-12-13,2017-12-03,NULL,121,650.594.0907,9283 Ruth St #81,Dormers Wells Ward,NULL,UB1 2FH,27
161,Sarath,Melissa,Sewall,9,168000.00,1958-08-27,2002-08-02,80,146,011.689.3207,9960 Gilroy Rd,Woodhouse Ward,NULL,N12 9JT,27
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
159,Lindsey,Ben,Smith,9,192000.00,1971-06-12,2010-06-24,80,146,011.988.3137,5588 Lake St #903,Crystal Palace Ward,NULL,SE19 2TJ,27
171,Ashley,Freya,Smith,9,177600.00,1979-12-07,2007-12-09,80,148,011.721.4298,62 Euston St,Bunhill Ward,NULL,EC1Y 8RT,27
173,Clark,Nigel,Solomon,9,146400.00,1965-02-07,2012-02-28,80,148,011.194.3517,684 Cotswold St,Victoria Ward,NULL,E9 7NG,27
113,Richard,Mark,Stewart,5,165600.00,1967-10-20,2003-10-13,100,108,515.239.5085,16949 Harristown Rd,Sydney,New South Wales,2287,2
138,Stephen,Curtis,Stiles,13,76800.00,1982-11-13,2018-11-09,50,123,650.538.5633,4403 Iowa Drive,Seattle,Washington,98127,28
182,Martha,NULL,Sullivan,14,60000.00,1960-08-04,2011-08-24,NULL,120,650.664.6703,1 Jervis St,High Barnet Ward,NULL,EN5 4LH,27
157,Patrick,Richard,Sully,9,228000.00,1993-09-20,2017-09-16,80,146,011.676.0988,2 Kirkdale Rd,Canning Town North Ward,NULL,E16 4NF,27
198,Alfred,Jack,Tate,14,62400.00,1991-04-03,2015-04-18,NULL,124,650.413.1564,65898 E St Nw,Watsonville,Queensland,4887,2
180,Horacio,Otis,Taylor,14,76800.00,1971-11-06,2005-11-21,NULL,120,650.021.8548,91 Ludlow St,Woodhouse Ward,NULL,N12 0EF,27
176,Aron,NULL,Taylor,9,206400.00,1960-08-21,2004-08-14,80,149,011.191.4554,76 Paulton St,Lancaster Gate Ward,NULL,W2 3JT,27
150,Peter,NULL,Tucker,9,240000.00,1989-04-28,2012-04-09,80,145,011.488.6311,45 Bidder St #38,Town Ward,NULL,EN1 3HT,27
155,Oliver,NULL,Tuvault,9,168000.00,1983-10-02,2002-10-16,80,145,011.254.0417,52 Trowbridge St,Knightsbridge and Belgravia Wa,NULL,SW1X 9HB,27
144,Peter,Andrew,Vargas,13,60000.00,1975-05-24,2001-05-26,50,124,650.989.6665,764 Knutson Avenue,Seattle,Washington,98166,28
162,Clara,NULL,Vishney,9,252000.00,1978-12-23,2013-12-18,80,147,011.059.1453,4 Northbrook St #600,Edmonton Green Ward,NULL,N18 2NF,27
123,Shanta,NULL,Vollman,12,156000.00,1984-07-06,2002-07-09,50,100,650.878.7210,45623 Lyons Street,Seattle,Washington,98148,28
196,Tabitha,Meghan,Walsh,14,74400.00,1991-04-02,2013-04-26,NULL,124,650.968.2599,9591 Bayshore Rd #637,Mirrool,New South Wales,2665,2
103,Yani,Michelle,Wenzlick,15,216000.00,1967-09-22,2002-09-06,60,102,590.117.7119,6 Pearson Junction,Seattle,Washington,98148,28
200,Jennifer,Patricia,Whalen,3,105600.00,1983-11-15,2007-11-06,NULL,101,515.551.7720,98247 Russell Blvd,Stafford Heights,Queensland,4053,2
120,Matthew,Anthony,Wilson,12,196800.00,1970-10-13,2011-10-14,50,100,650.689.6900,91 Northland Plaza,Seattle,Washington,98127,28

### **Second Challenge**  

Challenge: Write a query that returns all employees ordered by salary from highest to lowest.

In [3]:
SELECT * FROM hcm.employees 
ORDER BY salary DESC;

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
100,Jack,John,Bernard,1,576000.00,1994-01-13,2017-01-23,90,NULL,515.996.5357,3 Kenwood Plaza,Seattle,Washington,98185,28
101,Don,Fred,Reilly,2,408000.00,1966-12-27,2006-12-28,90,100,515.848.4385,61 Banding Street,Seattle,Washington,98166,28
102,Judy,Georgia,Lawson,2,408000.00,1960-11-12,2010-11-26,90,100,515.195.9617,17 American Ash Trail,Seattle,Washington,98127,28
145,Harold,John,Russell,8,336000.00,1969-01-06,2004-01-15,80,100,011.781.2573,67 Micawber St,Brockley Ward,NULL,SE14 6RQ,27
146,Karen,Courtney,Partners,8,336000.00,1986-12-06,2002-12-14,80,100,011.116.5962,41 Benedict St,Aldborough Ward,NULL,IG2 7QG,27
201,Michael,Timothy,Hartstein,16,312000.00,1965-07-11,2010-07-04,NULL,100,515.533.9401,423 S Navajo St #56,Brookhill,Queensland,4816,2
205,Shelley,NULL,Higgins,6,288192.00,1975-04-04,2015-04-10,NULL,101,515.509.9456,52347 San Fernando Rd,Coppabella,Queensland,4741,2
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
147,Alberto,Jesus,Errazuriz,8,288000.00,1973-08-17,2003-08-12,80,100,011.548.7376,62 Margaret St,Royal Hospital Ward,NULL,SW3 4ND,27
168,Danny,NULL,Ozer,9,276000.00,1990-03-28,2014-03-04,80,148,011.597.1458,1779 Bird St,East Sheen Ward,NULL,SW14 8JZ,27
148,Gerald,NULL,Cambrault,8,264000.00,1973-06-27,2013-06-26,80,100,011.869.8196,61 Miriam St,Abbey Road Ward,NULL,NW8 9BD,27
174,Annemarie,Olivia,Hoffman,9,264000.00,1975-08-04,2016-08-01,80,149,011.657.3709,231 Wordsworth St,Harrow Weald Ward,NULL,HA3 6TH,27
114,Diana,Mary,Colman,10,264000.00,1986-02-13,2013-02-20,30,100,515.776.5640,576 Nancy Alley,Seattle,Washington,98115,28
162,Clara,NULL,Vishney,9,252000.00,1978-12-23,2013-12-18,80,147,011.059.1453,4 Northbrook St #600,Edmonton Green Ward,NULL,N18 2NF,27
149,Michael,NULL,Rogers,8,252000.00,1970-10-19,2011-10-05,80,100,011.612.8871,5382 Redfern St,West End Ward,NULL,W1J 0QH,27
150,Peter,NULL,Tucker,9,240000.00,1989-04-28,2012-04-09,80,145,011.488.6311,45 Bidder St #38,Town Ward,NULL,EN1 3HT,27
156,Janette,Helen,King,9,240000.00,1989-09-28,2019-09-22,80,146,011.033.2021,3347 Lawrence Rd #456,Haverstock Ward,NULL,NW5 4EU,27
169,Alexander,Joseph,Bloom,9,240000.00,1964-09-23,2014-09-23,80,148,011.733.4576,7 Netley St,Custom House Ward,NULL,E16 3DP,27
204,Richard,Michael,Baer,19,240000.00,1961-04-07,2015-04-16,NULL,101,515.241.7574,5210 E Airy St #2,Brandy Creek,Queensland,4800,2
170,William,Nigel,Fox,9,230400.00,1992-07-13,2014-07-09,80,148,011.225.0992,2 Prince Rupert St,West Wickham Ward,NULL,BR3 6SX,27
157,Patrick,Richard,Sully,9,228000.00,1993-09-20,2017-09-16,80,146,011.676.0988,2 Kirkdale Rd,Canning Town North Ward,NULL,E16 4NF,27
163,Danielle,Marie,Greene,9,228000.00,1990-05-16,2012-05-05,80,147,011.093.1450,6301 Dorset Rd,Harefield Ward,NULL,UB9 6LF,27
151,David,NULL,Bernstein,9,228000.00,1963-04-07,2017-04-13,80,145,011.474.4371,5344 Bengel St #5,Millwall Ward,NULL,E14 5DR,27
152,Peter,NULL,Hall,9,216000.00,1994-05-11,2015-05-18,80,145,011.551.8183,227 Albert Terrace,Belvedere Ward,NULL,DA17 6EF,27
158,Allan,Arthur,McEwen,9,216000.00,1966-07-13,2010-07-26,80,146,011.734.7834,588 Venmore St,Twickenham Riverside Ward,NULL,TW1 2QH,27
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
103,Yani,Michelle,Wenzlick,15,216000.00,1967-09-22,2002-09-06,60,102,590.117.7119,6 Pearson Junction,Seattle,Washington,98148,28
175,Hiroko,NULL,Hutton,9,211200.00,1995-04-02,2018-04-27,80,149,011.181.1371,7252 Dansie St,East Finchley Ward,NULL,N2 9JL,27
176,Aron,NULL,Taylor,9,206400.00,1960-08-21,2004-08-14,80,149,011.191.4554,76 Paulton St,Lancaster Gate Ward,NULL,W2 3JT,27
177,Theron,NULL,Livingston,9,201600.00,1988-08-20,2013-08-24,80,149,011.283.5306,1257 Stone St,Northwood Ward,NULL,HA6 1AN,27
206,William,Abe,Gietz,7,199200.00,1962-10-24,2016-10-16,NULL,205,515.598.9812,15126 Goldenwest St,Toowoomba South,Queensland,4350,2
110,John,NULL,Chen,5,196800.00,1961-01-24,2007-01-06,100,108,515.003.1575,406 Eastern road,Sydney,New South Wales,2481,2
120,Matthew,Anthony,Wilson,12,196800.00,1970-10-13,2011-10-14,50,100,650.689.6900,91 Northland Plaza,Seattle,Washington,98127,28
121,Jack,Earl,Hale,12,196800.00,1966-09-13,2011-09-07,50,100,650.083.4633,3951 Merrick Lane,Seattle,Washington,98133,28
159,Lindsey,Ben,Smith,9,192000.00,1971-06-12,2010-06-24,80,146,011.988.3137,5588 Lake St #903,Crystal Palace Ward,NULL,SE19 2TJ,27
153,Christopher,NULL,Olsen,9,192000.00,1958-10-13,2007-10-12,80,145,011.628.3870,464 Back Nile St #618,Acton Central Ward,NULL,W3 6QJ,27
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
112,Lena,Michelle,Chadwick,5,187200.00,1957-02-03,2004-02-04,100,108,515.390.5375,6 Argyle Rd,Sydney,New South Wales,2300,2
111,Llyod,Eric,Henderson,5,184800.00,1992-10-02,2016-10-07,100,108,515.689.5566,60 Highway Road,Sydney,New South Wales,2155,2
154,Raewyn,Phoebe,Cambrault,9,180000.00,1985-10-25,2010-10-05,80,145,011.903.1413,76 Dawber St #6,Blackheath Westcombe Ward,NULL,SE3 7JY,27
160,Louise,Christina,Doran,9,180000.00,1971-01-25,2010-01-20,80,146,011.432.6996,5 Gainsborough Rd,Newington Ward,NULL,SE1 6EH,27
171,Ashley,Freya,Smith,9,177600.00,1979-12-07,2007-12-09,80,148,011.721.4298,62 Euston St,Bunhill Ward,NULL,EC1Y 8RT,27
172,Edward,Neil,Bates,9,175200.00,1968-02-04,2014-02-09,80,148,011.649.3798,7901 Beech St,St. Helier Ward,NULL,SM4 5PY,27
164,Tamara,Madeleine,Marvins,9,172800.00,1963-09-14,2001-09-15,80,147,011.316.1849,11 Tetlow St,Parsons Green and Walham Ward,NULL,SW6 4QP,27
161,Sarath,Melissa,Sewall,9,168000.00,1958-08-27,2002-08-02,80,146,011.689.3207,9960 Gilroy Rd,Woodhouse Ward,NULL,N12 9JT,27
178,Olivia,Chantelle,Grant,9,168000.00,1995-06-26,2013-06-05,NULL,149,011.486.1642,5 Bentinck St,Churchill Ward,NULL,SW1V 3EW,27
155,Oliver,NULL,Tuvault,9,168000.00,1983-10-02,2002-10-16,80,145,011.254.0417,52 Trowbridge St,Knightsbridge and Belgravia Wa,NULL,SW1X 9HB,27
113,Richard,Mark,Stewart,5,165600.00,1967-10-20,2003-10-13,100,108,515.239.5085,16949 Harristown Rd,Sydney,New South Wales,2287,2
165,David,Craig,Lee,9,163200.00,1987-07-03,2010-07-13,80,147,011.322.6428,22 Kilshaw St,Wimbledon Park Ward,NULL,SW19 7DT,27
123,Shanta,NULL,Vollman,12,156000.00,1984-07-06,2002-07-09,50,100,650.878.7210,45623 Lyons Street,Seattle,Washington,98148,28
203,Susan,Jane,Jacobs,18,156000.00,1985-07-11,2012-07-19,NULL,101,515.541.4415,4 Piccadilly Place,Manchester,NULL,M1 3BG,27
166,Sundar,NULL,Ande,9,153600.00,1995-06-12,2014-06-21,80,147,011.069.6306,9923 Dinorben St #4838,Childs Hill Ward,NULL,NW11 8DY,27
167,Amit,Tom,Banda,9,148800.00,1978-05-09,2017-05-28,80,147,011.910.9493,7643 Campbell St,Penge and Cator Ward,NULL,BR3 1LT,27
179,Richie,Hugh,Johnson,9,148800.00,1977-11-17,2010-11-20,NULL,149,011.823.8442,7 Canton St,Mildmay Ward,NULL,N1 4RF,27
173,Clark,Nigel,Solomon,9,146400.00,1965-02-07,2012-02-28,80,148,011.194.3517,684 Cotswold St,Victoria Ward,NULL,E9 7NG,27
202,Patrick,Ronan,Bacon,17,144000.00,1993-11-10,2013-11-04,NULL,201,603.241.7070,92 South St,Alligator Creek,Queensland,4740,2
104,Rachel,Alison,Mortensen,15,144000.00,1959-07-27,2003-07-25,60,103,590.876.6936,27 Dunning Street,Seattle,Washington,98109,28
124,Kevin,NULL,Mourgos,12,139200.00,1970-09-03,2009-09-21,50,100,650.168.8824,52 Hollow Ridge Street,Seattle,Washington,98148,28
105,Paul,James,Cameron,15,115200.00,1985-12-20,2018-12-14,60,103,590.826.7764,3 Calypso Parkway,Seattle,Washington,98133,28
106,Russell,John,King,15,115200.00,1989-04-18,2008-04-21,60,103,590.964.4035,5 Barnett Drive,Seattle,Washington,98148,28
200,Jennifer,Patricia,Whalen,3,105600.00,1983-11-15,2007-11-06,NULL,101,515.551.7720,98247 Russell Blvd,Stafford Heights,Queensland,4053,2
184,Nandita,NULL,Sarchand,14,100800.00,1975-12-13,2017-12-03,NULL,121,650.594.0907,9283 Ruth St #81,Dormers Wells Ward,NULL,UB1 2FH,27
107,Maria,April,Cameron,15,100800.00,1973-03-11,2008-03-01,60,103,590.643.5171,578 Brentwood Parkway,Seattle,Washington,98140,28
185,Alexis,NULL,Bull,14,98400.00,1963-03-26,2013-03-26,NULL,121,650.315.7253,6452 Pilgrim St #5,Seven Sisters Ward,NULL,N15 6TH,27
192,Sarah,Maisie,Bell,14,96000.00,1969-04-05,2013-04-22,NULL,123,650.950.5406,5399 Mcwhorter Rd,Calala,New South Wales,2340,2
193,Britney,Josie,Everett,14,93600.00,1958-01-01,2011-01-10,NULL,123,650.830.8731,7 Hall St,Nambucca Heads,New South Wales,2448,2
188,Kelly,Natalie,Chung,14,91200.00,1968-12-14,2009-12-07,NULL,122,650.825.3939,3 S Willow St #82,Bygalorie,New South Wales,2669,2
189,Jennifer,Hazel,Dilly,14,86400.00,1957-12-26,2018-12-20,NULL,122,650.517.8059,199 Maple Ave,Boolaroo,New South Wales,2284,2
137,Renske,NULL,Ladwig,13,86400.00,1972-07-18,2006-07-15,50,123,650.960.5034,8 Upham Crossing,Seattle,Washington,98127,28
141,Trenna,Jasmine,Rajs,13,84000.00,1965-09-27,2006-09-19,50,124,650.295.9197,6896 Reindahl Parkway,Seattle,Washington,98115,28
186,Julia,Veronica,Dellinger,14,81600.00,1977-01-08,2005-01-06,NULL,121,650.297.2123,70 Lilly Rd,Shirley Ward,NULL,CR0 7PT,27
129,Laura,Tanya,Bissot,13,79200.00,1987-04-02,2016-04-08,50,121,650.824.8471,5378 Porter Place,Seattle,Washington,98195,28
133,Jason,Paul,Mallin,13,79200.00,1985-12-22,2016-12-06,50,122,650.315.4723,7975 Pleasure Crossing,Seattle,Washington,98166,28
125,Julia,Aleisha,Nayer,13,76800.00,1972-09-16,2015-09-17,50,120,650.290.0080,7 Summerview Crossing,Seattle,Washington,98109,28
138,Stephen,Curtis,Stiles,13,76800.00,1982-11-13,2018-11-09,50,123,650.538.5633,4403 Iowa Drive,Seattle,Washington,98127,28
180,Horacio,Otis,Taylor,14,76800.00,1971-11-06,2005-11-21,NULL,120,650.021.8548,91 Ludlow St,Woodhouse Ward,NULL,N12 0EF,27
194,Samuel,Christopher,McCain,14,76800.00,1985-06-27,2017-06-09,NULL,123,650.864.7855,5 W Allen St,Mccullys Gap,New South Wales,2333,2
196,Tabitha,Meghan,Walsh,14,74400.00,1991-04-02,2013-04-26,NULL,124,650.968.2599,9591 Bayshore Rd #637,Mirrool,New South Wales,2665,2
181,Laura,Caitlyn,Hobbs,14,74400.00,1977-10-07,2014-10-23,NULL,120,650.104.4982,2476 Marsh St,Markhouse Ward,NULL,E17 8NP,27
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
115,Alexander,NULL,Khoo,11,74400.00,1959-10-17,2011-10-04,30,114,515.125.0259,22270 Portage Park,Seattle,Washington,98104,28
197,Milford,NULL,Feeney,14,72000.00,1962-06-10,2010-06-26,NULL,124,650.523.2373,6 Hope Rd #10,Pinnacle,Queensland,4741,2
187,Anthony,Alec,Cabrio,14,72000.00,1980-12-18,2014-12-08,NULL,121,650.107.6163,9166 Devon St #905,Knightsbridge and Belgravia Wa,NULL,SW1W 8JY,27
190,Timothy,Mitchell,Gates,14,69600.00,1983-02-01,2018-02-08,NULL,122,650.340.2668,5 30w W #3083,Hillston,New South Wales,2675,2
116,Shelli,NULL,Baida,11,69600.00,1959-01-23,2016-01-10,30,114,515.513.4164,05 School Lane,Seattle,Washington,98121,28
134,Michael,Robert,Rogers,13,69600.00,1969-08-25,2018-08-22,50,122,650.763.3210,212 High Crossing Terrace,Seattle,Washington,98148,28
130,Mark,Jeffrey,Atkinson,13,67200.00,1979-02-04,2010-02-25,50,121,650.447.4686,94307 Annamark Junction,Seattle,Washington,98104,28
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
195,Catrina,Hollie,Jones,14,67200.00,1957-02-17,2005-02-19,NULL,123,650.146.4730,28 Aaronwood Ave Ne,Coombell,New South Wales,2470,2
183,Girard,Rafael,Geoni,14,67200.00,1965-08-02,2018-08-24,NULL,120,650.244.2292,2015 Suburban Rd,Springfield Ward,NULL,N16 6TD,27
126,Irene,NULL,Mikkilineni,13,64800.00,1962-02-16,2001-02-22,50,120,650.810.3548,6 Veith Place,Seattle,Washington,98115,28
139,Tony,Sean,Rogers,13,64800.00,1976-02-21,2017-02-12,50,123,650.250.0801,89 Randy Junction,Seattle,Washington,98109,28
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
198,Alfred,Jack,Tate,14,62400.00,1991-04-03,2015-04-18,NULL,124,650.413.1564,65898 E St Nw,Watsonville,Queensland,4887,2
199,Douglas,Robert,Grant,14,62400.00,1993-02-04,2016-02-25,NULL,124,650.742.9288,35673 Annapolis Rd #190,Ascot,Queensland,4359,2
191,Chuck,NULL,Perkins,14,60000.00,1994-03-01,2015-03-20,NULL,122,650.749.2243,6940 Prospect Pl,Caldwell,New South Wales,2710,2
119,Karen,Rhonda,Colmenares,11,60000.00,1987-03-06,2006-03-04,30,114,515.593.3752,23 Kennedy Drive,Seattle,Washington,98166,28
131,James,Ian,Marlow,13,60000.00,1984-06-21,2013-06-09,50,121,650.860.2883,1891 Sage Court,Seattle,Washington,98109,28
144,Peter,Andrew,Vargas,13,60000.00,1975-05-24,2001-05-26,50,124,650.989.6665,764 Knutson Avenue,Seattle,Washington,98166,28
140,Mayank,NULL,Patel,13,60000.00,1983-06-16,2010-06-05,50,123,650.281.1672,2954 North Plaza,Seattle,Washington,98104,28
182,Martha,NULL,Sullivan,14,60000.00,1960-08-04,2011-08-24,NULL,120,650.664.6703,1 Jervis St,High Barnet Ward,NULL,EN5 4LH,27
135,Mitch,Matthew,Holt,13,57600.00,1992-05-10,2012-05-23,50,122,650.500.8591,3 Muir Trail,Seattle,Washington,98104,28
127,James,NULL,Landry,13,57600.00,1972-04-13,2011-04-11,50,120,650.816.0130,95 Elka Crossing,Seattle,Washington,98109,28
128,Steven,Andrew,Markle,13,52800.00,1970-08-19,2004-08-01,50,120,650.058.3953,18499 Autumn Leaf Trail,Seattle,Washington,98185,28
136,Hazel,Danielle,Philtanker,13,52800.00,1994-10-17,2017-10-13,50,122,650.908.2415,8 South Avenue,Seattle,Washington,98185,28
132,Gavin,Francis,Olson,13,52800.00,1973-02-16,2008-02-15,50,121,650.283.1659,9794 Carey Hill,Seattle,Washington,98109,28

### **Third Challenge**  

Challenge: Write a query to return all employees ordered by most recently hired to longest serving.

In [4]:
SELECT * FROM hcm.employees 
ORDER BY hire_date DESC;

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
156,Janette,Helen,King,9,240000.00,1989-09-28,2019-09-22,80,146,011.033.2021,3347 Lawrence Rd #456,Haverstock Ward,NULL,NW5 4EU,27
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
189,Jennifer,Hazel,Dilly,14,86400.00,1957-12-26,2018-12-20,NULL,122,650.517.8059,199 Maple Ave,Boolaroo,New South Wales,2284,2
105,Paul,James,Cameron,15,115200.00,1985-12-20,2018-12-14,60,103,590.826.7764,3 Calypso Parkway,Seattle,Washington,98133,28
138,Stephen,Curtis,Stiles,13,76800.00,1982-11-13,2018-11-09,50,123,650.538.5633,4403 Iowa Drive,Seattle,Washington,98127,28
183,Girard,Rafael,Geoni,14,67200.00,1965-08-02,2018-08-24,NULL,120,650.244.2292,2015 Suburban Rd,Springfield Ward,NULL,N16 6TD,27
134,Michael,Robert,Rogers,13,69600.00,1969-08-25,2018-08-22,50,122,650.763.3210,212 High Crossing Terrace,Seattle,Washington,98148,28
175,Hiroko,NULL,Hutton,9,211200.00,1995-04-02,2018-04-27,80,149,011.181.1371,7252 Dansie St,East Finchley Ward,NULL,N2 9JL,27
190,Timothy,Mitchell,Gates,14,69600.00,1983-02-01,2018-02-08,NULL,122,650.340.2668,5 30w W #3083,Hillston,New South Wales,2675,2
184,Nandita,NULL,Sarchand,14,100800.00,1975-12-13,2017-12-03,NULL,121,650.594.0907,9283 Ruth St #81,Dormers Wells Ward,NULL,UB1 2FH,27
136,Hazel,Danielle,Philtanker,13,52800.00,1994-10-17,2017-10-13,50,122,650.908.2415,8 South Avenue,Seattle,Washington,98185,28
157,Patrick,Richard,Sully,9,228000.00,1993-09-20,2017-09-16,80,146,011.676.0988,2 Kirkdale Rd,Canning Town North Ward,NULL,E16 4NF,27
194,Samuel,Christopher,McCain,14,76800.00,1985-06-27,2017-06-09,NULL,123,650.864.7855,5 W Allen St,Mccullys Gap,New South Wales,2333,2
167,Amit,Tom,Banda,9,148800.00,1978-05-09,2017-05-28,80,147,011.910.9493,7643 Campbell St,Penge and Cator Ward,NULL,BR3 1LT,27
151,David,NULL,Bernstein,9,228000.00,1963-04-07,2017-04-13,80,145,011.474.4371,5344 Bengel St #5,Millwall Ward,NULL,E14 5DR,27
139,Tony,Sean,Rogers,13,64800.00,1976-02-21,2017-02-12,50,123,650.250.0801,89 Randy Junction,Seattle,Washington,98109,28
100,Jack,John,Bernard,1,576000.00,1994-01-13,2017-01-23,90,NULL,515.996.5357,3 Kenwood Plaza,Seattle,Washington,98185,28
133,Jason,Paul,Mallin,13,79200.00,1985-12-22,2016-12-06,50,122,650.315.4723,7975 Pleasure Crossing,Seattle,Washington,98166,28
206,William,Abe,Gietz,7,199200.00,1962-10-24,2016-10-16,NULL,205,515.598.9812,15126 Goldenwest St,Toowoomba South,Queensland,4350,2
111,Llyod,Eric,Henderson,5,184800.00,1992-10-02,2016-10-07,100,108,515.689.5566,60 Highway Road,Sydney,New South Wales,2155,2
174,Annemarie,Olivia,Hoffman,9,264000.00,1975-08-04,2016-08-01,80,149,011.657.3709,231 Wordsworth St,Harrow Weald Ward,NULL,HA3 6TH,27
129,Laura,Tanya,Bissot,13,79200.00,1987-04-02,2016-04-08,50,121,650.824.8471,5378 Porter Place,Seattle,Washington,98195,28
199,Douglas,Robert,Grant,14,62400.00,1993-02-04,2016-02-25,NULL,124,650.742.9288,35673 Annapolis Rd #190,Ascot,Queensland,4359,2
116,Shelli,NULL,Baida,11,69600.00,1959-01-23,2016-01-10,30,114,515.513.4164,05 School Lane,Seattle,Washington,98121,28
125,Julia,Aleisha,Nayer,13,76800.00,1972-09-16,2015-09-17,50,120,650.290.0080,7 Summerview Crossing,Seattle,Washington,98109,28
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
152,Peter,NULL,Hall,9,216000.00,1994-05-11,2015-05-18,80,145,011.551.8183,227 Albert Terrace,Belvedere Ward,NULL,DA17 6EF,27
198,Alfred,Jack,Tate,14,62400.00,1991-04-03,2015-04-18,NULL,124,650.413.1564,65898 E St Nw,Watsonville,Queensland,4887,2
204,Richard,Michael,Baer,19,240000.00,1961-04-07,2015-04-16,NULL,101,515.241.7574,5210 E Airy St #2,Brandy Creek,Queensland,4800,2
205,Shelley,NULL,Higgins,6,288192.00,1975-04-04,2015-04-10,NULL,101,515.509.9456,52347 San Fernando Rd,Coppabella,Queensland,4741,2
191,Chuck,NULL,Perkins,14,60000.00,1994-03-01,2015-03-20,NULL,122,650.749.2243,6940 Prospect Pl,Caldwell,New South Wales,2710,2
187,Anthony,Alec,Cabrio,14,72000.00,1980-12-18,2014-12-08,NULL,121,650.107.6163,9166 Devon St #905,Knightsbridge and Belgravia Wa,NULL,SW1W 8JY,27
181,Laura,Caitlyn,Hobbs,14,74400.00,1977-10-07,2014-10-23,NULL,120,650.104.4982,2476 Marsh St,Markhouse Ward,NULL,E17 8NP,27
169,Alexander,Joseph,Bloom,9,240000.00,1964-09-23,2014-09-23,80,148,011.733.4576,7 Netley St,Custom House Ward,NULL,E16 3DP,27
170,William,Nigel,Fox,9,230400.00,1992-07-13,2014-07-09,80,148,011.225.0992,2 Prince Rupert St,West Wickham Ward,NULL,BR3 6SX,27
166,Sundar,NULL,Ande,9,153600.00,1995-06-12,2014-06-21,80,147,011.069.6306,9923 Dinorben St #4838,Childs Hill Ward,NULL,NW11 8DY,27
168,Danny,NULL,Ozer,9,276000.00,1990-03-28,2014-03-04,80,148,011.597.1458,1779 Bird St,East Sheen Ward,NULL,SW14 8JZ,27
172,Edward,Neil,Bates,9,175200.00,1968-02-04,2014-02-09,80,148,011.649.3798,7901 Beech St,St. Helier Ward,NULL,SM4 5PY,27
162,Clara,NULL,Vishney,9,252000.00,1978-12-23,2013-12-18,80,147,011.059.1453,4 Northbrook St #600,Edmonton Green Ward,NULL,N18 2NF,27
202,Patrick,Ronan,Bacon,17,144000.00,1993-11-10,2013-11-04,NULL,201,603.241.7070,92 South St,Alligator Creek,Queensland,4740,2
177,Theron,NULL,Livingston,9,201600.00,1988-08-20,2013-08-24,80,149,011.283.5306,1257 Stone St,Northwood Ward,NULL,HA6 1AN,27
148,Gerald,NULL,Cambrault,8,264000.00,1973-06-27,2013-06-26,80,100,011.869.8196,61 Miriam St,Abbey Road Ward,NULL,NW8 9BD,27
131,James,Ian,Marlow,13,60000.00,1984-06-21,2013-06-09,50,121,650.860.2883,1891 Sage Court,Seattle,Washington,98109,28
178,Olivia,Chantelle,Grant,9,168000.00,1995-06-26,2013-06-05,NULL,149,011.486.1642,5 Bentinck St,Churchill Ward,NULL,SW1V 3EW,27
196,Tabitha,Meghan,Walsh,14,74400.00,1991-04-02,2013-04-26,NULL,124,650.968.2599,9591 Bayshore Rd #637,Mirrool,New South Wales,2665,2
192,Sarah,Maisie,Bell,14,96000.00,1969-04-05,2013-04-22,NULL,123,650.950.5406,5399 Mcwhorter Rd,Calala,New South Wales,2340,2
185,Alexis,NULL,Bull,14,98400.00,1963-03-26,2013-03-26,NULL,121,650.315.7253,6452 Pilgrim St #5,Seven Sisters Ward,NULL,N15 6TH,27
114,Diana,Mary,Colman,10,264000.00,1986-02-13,2013-02-20,30,100,515.776.5640,576 Nancy Alley,Seattle,Washington,98115,28
203,Susan,Jane,Jacobs,18,156000.00,1985-07-11,2012-07-19,NULL,101,515.541.4415,4 Piccadilly Place,Manchester,NULL,M1 3BG,27
135,Mitch,Matthew,Holt,13,57600.00,1992-05-10,2012-05-23,50,122,650.500.8591,3 Muir Trail,Seattle,Washington,98104,28
163,Danielle,Marie,Greene,9,228000.00,1990-05-16,2012-05-05,80,147,011.093.1450,6301 Dorset Rd,Harefield Ward,NULL,UB9 6LF,27
150,Peter,NULL,Tucker,9,240000.00,1989-04-28,2012-04-09,80,145,011.488.6311,45 Bidder St #38,Town Ward,NULL,EN1 3HT,27
173,Clark,Nigel,Solomon,9,146400.00,1965-02-07,2012-02-28,80,148,011.194.3517,684 Cotswold St,Victoria Ward,NULL,E9 7NG,27
120,Matthew,Anthony,Wilson,12,196800.00,1970-10-13,2011-10-14,50,100,650.689.6900,91 Northland Plaza,Seattle,Washington,98127,28
149,Michael,NULL,Rogers,8,252000.00,1970-10-19,2011-10-05,80,100,011.612.8871,5382 Redfern St,West End Ward,NULL,W1J 0QH,27
115,Alexander,NULL,Khoo,11,74400.00,1959-10-17,2011-10-04,30,114,515.125.0259,22270 Portage Park,Seattle,Washington,98104,28
121,Jack,Earl,Hale,12,196800.00,1966-09-13,2011-09-07,50,100,650.083.4633,3951 Merrick Lane,Seattle,Washington,98133,28
182,Martha,NULL,Sullivan,14,60000.00,1960-08-04,2011-08-24,NULL,120,650.664.6703,1 Jervis St,High Barnet Ward,NULL,EN5 4LH,27
127,James,NULL,Landry,13,57600.00,1972-04-13,2011-04-11,50,120,650.816.0130,95 Elka Crossing,Seattle,Washington,98109,28
193,Britney,Josie,Everett,14,93600.00,1958-01-01,2011-01-10,NULL,123,650.830.8731,7 Hall St,Nambucca Heads,New South Wales,2448,2
102,Judy,Georgia,Lawson,2,408000.00,1960-11-12,2010-11-26,90,100,515.195.9617,17 American Ash Trail,Seattle,Washington,98127,28
179,Richie,Hugh,Johnson,9,148800.00,1977-11-17,2010-11-20,NULL,149,011.823.8442,7 Canton St,Mildmay Ward,NULL,N1 4RF,27
154,Raewyn,Phoebe,Cambrault,9,180000.00,1985-10-25,2010-10-05,80,145,011.903.1413,76 Dawber St #6,Blackheath Westcombe Ward,NULL,SE3 7JY,27
158,Allan,Arthur,McEwen,9,216000.00,1966-07-13,2010-07-26,80,146,011.734.7834,588 Venmore St,Twickenham Riverside Ward,NULL,TW1 2QH,27
165,David,Craig,Lee,9,163200.00,1987-07-03,2010-07-13,80,147,011.322.6428,22 Kilshaw St,Wimbledon Park Ward,NULL,SW19 7DT,27
201,Michael,Timothy,Hartstein,16,312000.00,1965-07-11,2010-07-04,NULL,100,515.533.9401,423 S Navajo St #56,Brookhill,Queensland,4816,2
197,Milford,NULL,Feeney,14,72000.00,1962-06-10,2010-06-26,NULL,124,650.523.2373,6 Hope Rd #10,Pinnacle,Queensland,4741,2
159,Lindsey,Ben,Smith,9,192000.00,1971-06-12,2010-06-24,80,146,011.988.3137,5588 Lake St #903,Crystal Palace Ward,NULL,SE19 2TJ,27
140,Mayank,NULL,Patel,13,60000.00,1983-06-16,2010-06-05,50,123,650.281.1672,2954 North Plaza,Seattle,Washington,98104,28
130,Mark,Jeffrey,Atkinson,13,67200.00,1979-02-04,2010-02-25,50,121,650.447.4686,94307 Annamark Junction,Seattle,Washington,98104,28
160,Louise,Christina,Doran,9,180000.00,1971-01-25,2010-01-20,80,146,011.432.6996,5 Gainsborough Rd,Newington Ward,NULL,SE1 6EH,27
188,Kelly,Natalie,Chung,14,91200.00,1968-12-14,2009-12-07,NULL,122,650.825.3939,3 S Willow St #82,Bygalorie,New South Wales,2669,2
124,Kevin,NULL,Mourgos,12,139200.00,1970-09-03,2009-09-21,50,100,650.168.8824,52 Hollow Ridge Street,Seattle,Washington,98148,28
106,Russell,John,King,15,115200.00,1989-04-18,2008-04-21,60,103,590.964.4035,5 Barnett Drive,Seattle,Washington,98148,28
107,Maria,April,Cameron,15,100800.00,1973-03-11,2008-03-01,60,103,590.643.5171,578 Brentwood Parkway,Seattle,Washington,98140,28
132,Gavin,Francis,Olson,13,52800.00,1973-02-16,2008-02-15,50,121,650.283.1659,9794 Carey Hill,Seattle,Washington,98109,28
171,Ashley,Freya,Smith,9,177600.00,1979-12-07,2007-12-09,80,148,011.721.4298,62 Euston St,Bunhill Ward,NULL,EC1Y 8RT,27
200,Jennifer,Patricia,Whalen,3,105600.00,1983-11-15,2007-11-06,NULL,101,515.551.7720,98247 Russell Blvd,Stafford Heights,Queensland,4053,2
153,Christopher,NULL,Olsen,9,192000.00,1958-10-13,2007-10-12,80,145,011.628.3870,464 Back Nile St #618,Acton Central Ward,NULL,W3 6QJ,27
110,John,NULL,Chen,5,196800.00,1961-01-24,2007-01-06,100,108,515.003.1575,406 Eastern road,Sydney,New South Wales,2481,2
101,Don,Fred,Reilly,2,408000.00,1966-12-27,2006-12-28,90,100,515.848.4385,61 Banding Street,Seattle,Washington,98166,28
141,Trenna,Jasmine,Rajs,13,84000.00,1965-09-27,2006-09-19,50,124,650.295.9197,6896 Reindahl Parkway,Seattle,Washington,98115,28
137,Renske,NULL,Ladwig,13,86400.00,1972-07-18,2006-07-15,50,123,650.960.5034,8 Upham Crossing,Seattle,Washington,98127,28
119,Karen,Rhonda,Colmenares,11,60000.00,1987-03-06,2006-03-04,30,114,515.593.3752,23 Kennedy Drive,Seattle,Washington,98166,28
180,Horacio,Otis,Taylor,14,76800.00,1971-11-06,2005-11-21,NULL,120,650.021.8548,91 Ludlow St,Woodhouse Ward,NULL,N12 0EF,27
195,Catrina,Hollie,Jones,14,67200.00,1957-02-17,2005-02-19,NULL,123,650.146.4730,28 Aaronwood Ave Ne,Coombell,New South Wales,2470,2
186,Julia,Veronica,Dellinger,14,81600.00,1977-01-08,2005-01-06,NULL,121,650.297.2123,70 Lilly Rd,Shirley Ward,NULL,CR0 7PT,27
176,Aron,NULL,Taylor,9,206400.00,1960-08-21,2004-08-14,80,149,011.191.4554,76 Paulton St,Lancaster Gate Ward,NULL,W2 3JT,27
128,Steven,Andrew,Markle,13,52800.00,1970-08-19,2004-08-01,50,120,650.058.3953,18499 Autumn Leaf Trail,Seattle,Washington,98185,28
112,Lena,Michelle,Chadwick,5,187200.00,1957-02-03,2004-02-04,100,108,515.390.5375,6 Argyle Rd,Sydney,New South Wales,2300,2
145,Harold,John,Russell,8,336000.00,1969-01-06,2004-01-15,80,100,011.781.2573,67 Micawber St,Brockley Ward,NULL,SE14 6RQ,27
113,Richard,Mark,Stewart,5,165600.00,1967-10-20,2003-10-13,100,108,515.239.5085,16949 Harristown Rd,Sydney,New South Wales,2287,2
147,Alberto,Jesus,Errazuriz,8,288000.00,1973-08-17,2003-08-12,80,100,011.548.7376,62 Margaret St,Royal Hospital Ward,NULL,SW3 4ND,27
104,Rachel,Alison,Mortensen,15,144000.00,1959-07-27,2003-07-25,60,103,590.876.6936,27 Dunning Street,Seattle,Washington,98109,28
146,Karen,Courtney,Partners,8,336000.00,1986-12-06,2002-12-14,80,100,011.116.5962,41 Benedict St,Aldborough Ward,NULL,IG2 7QG,27
155,Oliver,NULL,Tuvault,9,168000.00,1983-10-02,2002-10-16,80,145,011.254.0417,52 Trowbridge St,Knightsbridge and Belgravia Wa,NULL,SW1X 9HB,27
103,Yani,Michelle,Wenzlick,15,216000.00,1967-09-22,2002-09-06,60,102,590.117.7119,6 Pearson Junction,Seattle,Washington,98148,28
161,Sarath,Melissa,Sewall,9,168000.00,1958-08-27,2002-08-02,80,146,011.689.3207,9960 Gilroy Rd,Woodhouse Ward,NULL,N12 9JT,27
123,Shanta,NULL,Vollman,12,156000.00,1984-07-06,2002-07-09,50,100,650.878.7210,45623 Lyons Street,Seattle,Washington,98148,28
164,Tamara,Madeleine,Marvins,9,172800.00,1963-09-14,2001-09-15,80,147,011.316.1849,11 Tetlow St,Parsons Green and Walham Ward,NULL,SW6 4QP,27
144,Peter,Andrew,Vargas,13,60000.00,1975-05-24,2001-05-26,50,124,650.989.6665,764 Knutson Avenue,Seattle,Washington,98166,28
126,Irene,NULL,Mikkilineni,13,64800.00,1962-02-16,2001-02-22,50,120,650.810.3548,6 Veith Place,Seattle,Washington,98115,28

### **Fourth Challenge**  

Challenge: Write a query to return all employees ordered by department\_id in ascending order and within each department\_id, order by salary from highest to lowest.

In [5]:
SELECT * FROM hcm.employees 
ORDER BY department_id, salary DESC;

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
201,Michael,Timothy,Hartstein,16,312000.00,1965-07-11,2010-07-04,NULL,100,515.533.9401,423 S Navajo St #56,Brookhill,Queensland,4816,2
205,Shelley,NULL,Higgins,6,288192.00,1975-04-04,2015-04-10,NULL,101,515.509.9456,52347 San Fernando Rd,Coppabella,Queensland,4741,2
204,Richard,Michael,Baer,19,240000.00,1961-04-07,2015-04-16,NULL,101,515.241.7574,5210 E Airy St #2,Brandy Creek,Queensland,4800,2
206,William,Abe,Gietz,7,199200.00,1962-10-24,2016-10-16,NULL,205,515.598.9812,15126 Goldenwest St,Toowoomba South,Queensland,4350,2
178,Olivia,Chantelle,Grant,9,168000.00,1995-06-26,2013-06-05,NULL,149,011.486.1642,5 Bentinck St,Churchill Ward,NULL,SW1V 3EW,27
203,Susan,Jane,Jacobs,18,156000.00,1985-07-11,2012-07-19,NULL,101,515.541.4415,4 Piccadilly Place,Manchester,NULL,M1 3BG,27
179,Richie,Hugh,Johnson,9,148800.00,1977-11-17,2010-11-20,NULL,149,011.823.8442,7 Canton St,Mildmay Ward,NULL,N1 4RF,27
202,Patrick,Ronan,Bacon,17,144000.00,1993-11-10,2013-11-04,NULL,201,603.241.7070,92 South St,Alligator Creek,Queensland,4740,2
200,Jennifer,Patricia,Whalen,3,105600.00,1983-11-15,2007-11-06,NULL,101,515.551.7720,98247 Russell Blvd,Stafford Heights,Queensland,4053,2
184,Nandita,NULL,Sarchand,14,100800.00,1975-12-13,2017-12-03,NULL,121,650.594.0907,9283 Ruth St #81,Dormers Wells Ward,NULL,UB1 2FH,27
185,Alexis,NULL,Bull,14,98400.00,1963-03-26,2013-03-26,NULL,121,650.315.7253,6452 Pilgrim St #5,Seven Sisters Ward,NULL,N15 6TH,27
192,Sarah,Maisie,Bell,14,96000.00,1969-04-05,2013-04-22,NULL,123,650.950.5406,5399 Mcwhorter Rd,Calala,New South Wales,2340,2
193,Britney,Josie,Everett,14,93600.00,1958-01-01,2011-01-10,NULL,123,650.830.8731,7 Hall St,Nambucca Heads,New South Wales,2448,2
188,Kelly,Natalie,Chung,14,91200.00,1968-12-14,2009-12-07,NULL,122,650.825.3939,3 S Willow St #82,Bygalorie,New South Wales,2669,2
189,Jennifer,Hazel,Dilly,14,86400.00,1957-12-26,2018-12-20,NULL,122,650.517.8059,199 Maple Ave,Boolaroo,New South Wales,2284,2
186,Julia,Veronica,Dellinger,14,81600.00,1977-01-08,2005-01-06,NULL,121,650.297.2123,70 Lilly Rd,Shirley Ward,NULL,CR0 7PT,27
180,Horacio,Otis,Taylor,14,76800.00,1971-11-06,2005-11-21,NULL,120,650.021.8548,91 Ludlow St,Woodhouse Ward,NULL,N12 0EF,27
194,Samuel,Christopher,McCain,14,76800.00,1985-06-27,2017-06-09,NULL,123,650.864.7855,5 W Allen St,Mccullys Gap,New South Wales,2333,2
196,Tabitha,Meghan,Walsh,14,74400.00,1991-04-02,2013-04-26,NULL,124,650.968.2599,9591 Bayshore Rd #637,Mirrool,New South Wales,2665,2
181,Laura,Caitlyn,Hobbs,14,74400.00,1977-10-07,2014-10-23,NULL,120,650.104.4982,2476 Marsh St,Markhouse Ward,NULL,E17 8NP,27
187,Anthony,Alec,Cabrio,14,72000.00,1980-12-18,2014-12-08,NULL,121,650.107.6163,9166 Devon St #905,Knightsbridge and Belgravia Wa,NULL,SW1W 8JY,27
197,Milford,NULL,Feeney,14,72000.00,1962-06-10,2010-06-26,NULL,124,650.523.2373,6 Hope Rd #10,Pinnacle,Queensland,4741,2
190,Timothy,Mitchell,Gates,14,69600.00,1983-02-01,2018-02-08,NULL,122,650.340.2668,5 30w W #3083,Hillston,New South Wales,2675,2
195,Catrina,Hollie,Jones,14,67200.00,1957-02-17,2005-02-19,NULL,123,650.146.4730,28 Aaronwood Ave Ne,Coombell,New South Wales,2470,2
183,Girard,Rafael,Geoni,14,67200.00,1965-08-02,2018-08-24,NULL,120,650.244.2292,2015 Suburban Rd,Springfield Ward,NULL,N16 6TD,27
198,Alfred,Jack,Tate,14,62400.00,1991-04-03,2015-04-18,NULL,124,650.413.1564,65898 E St Nw,Watsonville,Queensland,4887,2
199,Douglas,Robert,Grant,14,62400.00,1993-02-04,2016-02-25,NULL,124,650.742.9288,35673 Annapolis Rd #190,Ascot,Queensland,4359,2
191,Chuck,NULL,Perkins,14,60000.00,1994-03-01,2015-03-20,NULL,122,650.749.2243,6940 Prospect Pl,Caldwell,New South Wales,2710,2
182,Martha,NULL,Sullivan,14,60000.00,1960-08-04,2011-08-24,NULL,120,650.664.6703,1 Jervis St,High Barnet Ward,NULL,EN5 4LH,27
114,Diana,Mary,Colman,10,264000.00,1986-02-13,2013-02-20,30,100,515.776.5640,576 Nancy Alley,Seattle,Washington,98115,28
115,Alexander,NULL,Khoo,11,74400.00,1959-10-17,2011-10-04,30,114,515.125.0259,22270 Portage Park,Seattle,Washington,98104,28
116,Shelli,NULL,Baida,11,69600.00,1959-01-23,2016-01-10,30,114,515.513.4164,05 School Lane,Seattle,Washington,98121,28
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
119,Karen,Rhonda,Colmenares,11,60000.00,1987-03-06,2006-03-04,30,114,515.593.3752,23 Kennedy Drive,Seattle,Washington,98166,28
120,Matthew,Anthony,Wilson,12,196800.00,1970-10-13,2011-10-14,50,100,650.689.6900,91 Northland Plaza,Seattle,Washington,98127,28
121,Jack,Earl,Hale,12,196800.00,1966-09-13,2011-09-07,50,100,650.083.4633,3951 Merrick Lane,Seattle,Washington,98133,28
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
123,Shanta,NULL,Vollman,12,156000.00,1984-07-06,2002-07-09,50,100,650.878.7210,45623 Lyons Street,Seattle,Washington,98148,28
124,Kevin,NULL,Mourgos,12,139200.00,1970-09-03,2009-09-21,50,100,650.168.8824,52 Hollow Ridge Street,Seattle,Washington,98148,28
137,Renske,NULL,Ladwig,13,86400.00,1972-07-18,2006-07-15,50,123,650.960.5034,8 Upham Crossing,Seattle,Washington,98127,28
141,Trenna,Jasmine,Rajs,13,84000.00,1965-09-27,2006-09-19,50,124,650.295.9197,6896 Reindahl Parkway,Seattle,Washington,98115,28
133,Jason,Paul,Mallin,13,79200.00,1985-12-22,2016-12-06,50,122,650.315.4723,7975 Pleasure Crossing,Seattle,Washington,98166,28
129,Laura,Tanya,Bissot,13,79200.00,1987-04-02,2016-04-08,50,121,650.824.8471,5378 Porter Place,Seattle,Washington,98195,28
138,Stephen,Curtis,Stiles,13,76800.00,1982-11-13,2018-11-09,50,123,650.538.5633,4403 Iowa Drive,Seattle,Washington,98127,28
125,Julia,Aleisha,Nayer,13,76800.00,1972-09-16,2015-09-17,50,120,650.290.0080,7 Summerview Crossing,Seattle,Washington,98109,28
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
134,Michael,Robert,Rogers,13,69600.00,1969-08-25,2018-08-22,50,122,650.763.3210,212 High Crossing Terrace,Seattle,Washington,98148,28
130,Mark,Jeffrey,Atkinson,13,67200.00,1979-02-04,2010-02-25,50,121,650.447.4686,94307 Annamark Junction,Seattle,Washington,98104,28
139,Tony,Sean,Rogers,13,64800.00,1976-02-21,2017-02-12,50,123,650.250.0801,89 Randy Junction,Seattle,Washington,98109,28
126,Irene,NULL,Mikkilineni,13,64800.00,1962-02-16,2001-02-22,50,120,650.810.3548,6 Veith Place,Seattle,Washington,98115,28
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28
144,Peter,Andrew,Vargas,13,60000.00,1975-05-24,2001-05-26,50,124,650.989.6665,764 Knutson Avenue,Seattle,Washington,98166,28
140,Mayank,NULL,Patel,13,60000.00,1983-06-16,2010-06-05,50,123,650.281.1672,2954 North Plaza,Seattle,Washington,98104,28
131,James,Ian,Marlow,13,60000.00,1984-06-21,2013-06-09,50,121,650.860.2883,1891 Sage Court,Seattle,Washington,98109,28
135,Mitch,Matthew,Holt,13,57600.00,1992-05-10,2012-05-23,50,122,650.500.8591,3 Muir Trail,Seattle,Washington,98104,28
127,James,NULL,Landry,13,57600.00,1972-04-13,2011-04-11,50,120,650.816.0130,95 Elka Crossing,Seattle,Washington,98109,28
128,Steven,Andrew,Markle,13,52800.00,1970-08-19,2004-08-01,50,120,650.058.3953,18499 Autumn Leaf Trail,Seattle,Washington,98185,28
136,Hazel,Danielle,Philtanker,13,52800.00,1994-10-17,2017-10-13,50,122,650.908.2415,8 South Avenue,Seattle,Washington,98185,28
132,Gavin,Francis,Olson,13,52800.00,1973-02-16,2008-02-15,50,121,650.283.1659,9794 Carey Hill,Seattle,Washington,98109,28
103,Yani,Michelle,Wenzlick,15,216000.00,1967-09-22,2002-09-06,60,102,590.117.7119,6 Pearson Junction,Seattle,Washington,98148,28
104,Rachel,Alison,Mortensen,15,144000.00,1959-07-27,2003-07-25,60,103,590.876.6936,27 Dunning Street,Seattle,Washington,98109,28
105,Paul,James,Cameron,15,115200.00,1985-12-20,2018-12-14,60,103,590.826.7764,3 Calypso Parkway,Seattle,Washington,98133,28
106,Russell,John,King,15,115200.00,1989-04-18,2008-04-21,60,103,590.964.4035,5 Barnett Drive,Seattle,Washington,98148,28
107,Maria,April,Cameron,15,100800.00,1973-03-11,2008-03-01,60,103,590.643.5171,578 Brentwood Parkway,Seattle,Washington,98140,28
145,Harold,John,Russell,8,336000.00,1969-01-06,2004-01-15,80,100,011.781.2573,67 Micawber St,Brockley Ward,NULL,SE14 6RQ,27
146,Karen,Courtney,Partners,8,336000.00,1986-12-06,2002-12-14,80,100,011.116.5962,41 Benedict St,Aldborough Ward,NULL,IG2 7QG,27
147,Alberto,Jesus,Errazuriz,8,288000.00,1973-08-17,2003-08-12,80,100,011.548.7376,62 Margaret St,Royal Hospital Ward,NULL,SW3 4ND,27
168,Danny,NULL,Ozer,9,276000.00,1990-03-28,2014-03-04,80,148,011.597.1458,1779 Bird St,East Sheen Ward,NULL,SW14 8JZ,27
174,Annemarie,Olivia,Hoffman,9,264000.00,1975-08-04,2016-08-01,80,149,011.657.3709,231 Wordsworth St,Harrow Weald Ward,NULL,HA3 6TH,27
148,Gerald,NULL,Cambrault,8,264000.00,1973-06-27,2013-06-26,80,100,011.869.8196,61 Miriam St,Abbey Road Ward,NULL,NW8 9BD,27
149,Michael,NULL,Rogers,8,252000.00,1970-10-19,2011-10-05,80,100,011.612.8871,5382 Redfern St,West End Ward,NULL,W1J 0QH,27
162,Clara,NULL,Vishney,9,252000.00,1978-12-23,2013-12-18,80,147,011.059.1453,4 Northbrook St #600,Edmonton Green Ward,NULL,N18 2NF,27
156,Janette,Helen,King,9,240000.00,1989-09-28,2019-09-22,80,146,011.033.2021,3347 Lawrence Rd #456,Haverstock Ward,NULL,NW5 4EU,27
150,Peter,NULL,Tucker,9,240000.00,1989-04-28,2012-04-09,80,145,011.488.6311,45 Bidder St #38,Town Ward,NULL,EN1 3HT,27
169,Alexander,Joseph,Bloom,9,240000.00,1964-09-23,2014-09-23,80,148,011.733.4576,7 Netley St,Custom House Ward,NULL,E16 3DP,27
170,William,Nigel,Fox,9,230400.00,1992-07-13,2014-07-09,80,148,011.225.0992,2 Prince Rupert St,West Wickham Ward,NULL,BR3 6SX,27
151,David,NULL,Bernstein,9,228000.00,1963-04-07,2017-04-13,80,145,011.474.4371,5344 Bengel St #5,Millwall Ward,NULL,E14 5DR,27
157,Patrick,Richard,Sully,9,228000.00,1993-09-20,2017-09-16,80,146,011.676.0988,2 Kirkdale Rd,Canning Town North Ward,NULL,E16 4NF,27
163,Danielle,Marie,Greene,9,228000.00,1990-05-16,2012-05-05,80,147,011.093.1450,6301 Dorset Rd,Harefield Ward,NULL,UB9 6LF,27
158,Allan,Arthur,McEwen,9,216000.00,1966-07-13,2010-07-26,80,146,011.734.7834,588 Venmore St,Twickenham Riverside Ward,NULL,TW1 2QH,27
152,Peter,NULL,Hall,9,216000.00,1994-05-11,2015-05-18,80,145,011.551.8183,227 Albert Terrace,Belvedere Ward,NULL,DA17 6EF,27
175,Hiroko,NULL,Hutton,9,211200.00,1995-04-02,2018-04-27,80,149,011.181.1371,7252 Dansie St,East Finchley Ward,NULL,N2 9JL,27
176,Aron,NULL,Taylor,9,206400.00,1960-08-21,2004-08-14,80,149,011.191.4554,76 Paulton St,Lancaster Gate Ward,NULL,W2 3JT,27
177,Theron,NULL,Livingston,9,201600.00,1988-08-20,2013-08-24,80,149,011.283.5306,1257 Stone St,Northwood Ward,NULL,HA6 1AN,27
153,Christopher,NULL,Olsen,9,192000.00,1958-10-13,2007-10-12,80,145,011.628.3870,464 Back Nile St #618,Acton Central Ward,NULL,W3 6QJ,27
159,Lindsey,Ben,Smith,9,192000.00,1971-06-12,2010-06-24,80,146,011.988.3137,5588 Lake St #903,Crystal Palace Ward,NULL,SE19 2TJ,27
160,Louise,Christina,Doran,9,180000.00,1971-01-25,2010-01-20,80,146,011.432.6996,5 Gainsborough Rd,Newington Ward,NULL,SE1 6EH,27
154,Raewyn,Phoebe,Cambrault,9,180000.00,1985-10-25,2010-10-05,80,145,011.903.1413,76 Dawber St #6,Blackheath Westcombe Ward,NULL,SE3 7JY,27
171,Ashley,Freya,Smith,9,177600.00,1979-12-07,2007-12-09,80,148,011.721.4298,62 Euston St,Bunhill Ward,NULL,EC1Y 8RT,27
172,Edward,Neil,Bates,9,175200.00,1968-02-04,2014-02-09,80,148,011.649.3798,7901 Beech St,St. Helier Ward,NULL,SM4 5PY,27
164,Tamara,Madeleine,Marvins,9,172800.00,1963-09-14,2001-09-15,80,147,011.316.1849,11 Tetlow St,Parsons Green and Walham Ward,NULL,SW6 4QP,27
161,Sarath,Melissa,Sewall,9,168000.00,1958-08-27,2002-08-02,80,146,011.689.3207,9960 Gilroy Rd,Woodhouse Ward,NULL,N12 9JT,27
155,Oliver,NULL,Tuvault,9,168000.00,1983-10-02,2002-10-16,80,145,011.254.0417,52 Trowbridge St,Knightsbridge and Belgravia Wa,NULL,SW1X 9HB,27
165,David,Craig,Lee,9,163200.00,1987-07-03,2010-07-13,80,147,011.322.6428,22 Kilshaw St,Wimbledon Park Ward,NULL,SW19 7DT,27
166,Sundar,NULL,Ande,9,153600.00,1995-06-12,2014-06-21,80,147,011.069.6306,9923 Dinorben St #4838,Childs Hill Ward,NULL,NW11 8DY,27
167,Amit,Tom,Banda,9,148800.00,1978-05-09,2017-05-28,80,147,011.910.9493,7643 Campbell St,Penge and Cator Ward,NULL,BR3 1LT,27
173,Clark,Nigel,Solomon,9,146400.00,1965-02-07,2012-02-28,80,148,011.194.3517,684 Cotswold St,Victoria Ward,NULL,E9 7NG,27
100,Jack,John,Bernard,1,576000.00,1994-01-13,2017-01-23,90,NULL,515.996.5357,3 Kenwood Plaza,Seattle,Washington,98185,28
101,Don,Fred,Reilly,2,408000.00,1966-12-27,2006-12-28,90,100,515.848.4385,61 Banding Street,Seattle,Washington,98166,28
102,Judy,Georgia,Lawson,2,408000.00,1960-11-12,2010-11-26,90,100,515.195.9617,17 American Ash Trail,Seattle,Washington,98127,28
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
110,John,NULL,Chen,5,196800.00,1961-01-24,2007-01-06,100,108,515.003.1575,406 Eastern road,Sydney,New South Wales,2481,2
112,Lena,Michelle,Chadwick,5,187200.00,1957-02-03,2004-02-04,100,108,515.390.5375,6 Argyle Rd,Sydney,New South Wales,2300,2
111,Llyod,Eric,Henderson,5,184800.00,1992-10-02,2016-10-07,100,108,515.689.5566,60 Highway Road,Sydney,New South Wales,2155,2
113,Richard,Mark,Stewart,5,165600.00,1967-10-20,2003-10-13,100,108,515.239.5085,16949 Harristown Rd,Sydney,New South Wales,2287,2

### **Fifth Challenge**  

Challenge: Write a query to return the employee\_id, first\_name, last\_name and salary for the top 10 employees who get paid the most.

In [6]:
SELECT TOP (10) employee_id, first_name, last_name, salary 
FROM hcm.employees 
ORDER BY salary DESC;

employee_id,first_name,last_name,salary
100,Jack,Bernard,576000.00
102,Judy,Lawson,408000.00
101,Don,Reilly,408000.00
145,Harold,Russell,336000.00
146,Karen,Partners,336000.00
201,Michael,Hartstein,312000.00
108,Patricia,Doyle,288192.00
205,Shelley,Higgins,288192.00
147,Alberto,Errazuriz,288000.00
168,Danny,Ozer,276000.00

### **Sixth Challenge**  

Challenge: Write a query to return the employee\_id, first\_name, last\_name and salary for the employee or employees who get paid the least.

In [7]:
SELECT TOP (1) WITH TIES employee_id, first_name, last_name, salary 
FROM hcm.employees 
ORDER BY salary;

employee_id,first_name,last_name,salary
128,Steven,Markle,52800.00
132,Gavin,Olson,52800.00
136,Hazel,Philtanker,52800.00