# Logical Operator Challenges

\*\*Use SampleDB Database\*\*

In [1]:
USE SAMPLEDB 
GO

### **First Challenge** 

Challenge: Select employees from the hcm.employees table who live in either Seattle or Sydney.

In [2]:
SELECT * FROM hcm.employees 
WHERE city IN ('Seattle', 'Sydney');

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
100,Jack,John,Bernard,1,576000.00,1994-01-13,2017-01-23,90,NULL,515.996.5357,3 Kenwood Plaza,Seattle,Washington,98185,28
101,Don,Fred,Reilly,2,408000.00,1966-12-27,2006-12-28,90,100,515.848.4385,61 Banding Street,Seattle,Washington,98166,28
102,Judy,Georgia,Lawson,2,408000.00,1960-11-12,2010-11-26,90,100,515.195.9617,17 American Ash Trail,Seattle,Washington,98127,28
103,Yani,Michelle,Wenzlick,15,216000.00,1967-09-22,2002-09-06,60,102,590.117.7119,6 Pearson Junction,Seattle,Washington,98148,28
104,Rachel,Alison,Mortensen,15,144000.00,1959-07-27,2003-07-25,60,103,590.876.6936,27 Dunning Street,Seattle,Washington,98109,28
105,Paul,James,Cameron,15,115200.00,1985-12-20,2018-12-14,60,103,590.826.7764,3 Calypso Parkway,Seattle,Washington,98133,28
106,Russell,John,King,15,115200.00,1989-04-18,2008-04-21,60,103,590.964.4035,5 Barnett Drive,Seattle,Washington,98148,28
107,Maria,April,Cameron,15,100800.00,1973-03-11,2008-03-01,60,103,590.643.5171,578 Brentwood Parkway,Seattle,Washington,98140,28
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
110,John,NULL,Chen,5,196800.00,1961-01-24,2007-01-06,100,108,515.003.1575,406 Eastern road,Sydney,New South Wales,2481,2
111,Llyod,Eric,Henderson,5,184800.00,1992-10-02,2016-10-07,100,108,515.689.5566,60 Highway Road,Sydney,New South Wales,2155,2
112,Lena,Michelle,Chadwick,5,187200.00,1957-02-03,2004-02-04,100,108,515.390.5375,6 Argyle Rd,Sydney,New South Wales,2300,2
113,Richard,Mark,Stewart,5,165600.00,1967-10-20,2003-10-13,100,108,515.239.5085,16949 Harristown Rd,Sydney,New South Wales,2287,2
114,Diana,Mary,Colman,10,264000.00,1986-02-13,2013-02-20,30,100,515.776.5640,576 Nancy Alley,Seattle,Washington,98115,28
115,Alexander,NULL,Khoo,11,74400.00,1959-10-17,2011-10-04,30,114,515.125.0259,22270 Portage Park,Seattle,Washington,98104,28
116,Shelli,NULL,Baida,11,69600.00,1959-01-23,2016-01-10,30,114,515.513.4164,05 School Lane,Seattle,Washington,98121,28
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
119,Karen,Rhonda,Colmenares,11,60000.00,1987-03-06,2006-03-04,30,114,515.593.3752,23 Kennedy Drive,Seattle,Washington,98166,28
120,Matthew,Anthony,Wilson,12,196800.00,1970-10-13,2011-10-14,50,100,650.689.6900,91 Northland Plaza,Seattle,Washington,98127,28
121,Jack,Earl,Hale,12,196800.00,1966-09-13,2011-09-07,50,100,650.083.4633,3951 Merrick Lane,Seattle,Washington,98133,28
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
123,Shanta,NULL,Vollman,12,156000.00,1984-07-06,2002-07-09,50,100,650.878.7210,45623 Lyons Street,Seattle,Washington,98148,28
124,Kevin,NULL,Mourgos,12,139200.00,1970-09-03,2009-09-21,50,100,650.168.8824,52 Hollow Ridge Street,Seattle,Washington,98148,28
125,Julia,Aleisha,Nayer,13,76800.00,1972-09-16,2015-09-17,50,120,650.290.0080,7 Summerview Crossing,Seattle,Washington,98109,28
126,Irene,NULL,Mikkilineni,13,64800.00,1962-02-16,2001-02-22,50,120,650.810.3548,6 Veith Place,Seattle,Washington,98115,28
127,James,NULL,Landry,13,57600.00,1972-04-13,2011-04-11,50,120,650.816.0130,95 Elka Crossing,Seattle,Washington,98109,28
128,Steven,Andrew,Markle,13,52800.00,1970-08-19,2004-08-01,50,120,650.058.3953,18499 Autumn Leaf Trail,Seattle,Washington,98185,28
129,Laura,Tanya,Bissot,13,79200.00,1987-04-02,2016-04-08,50,121,650.824.8471,5378 Porter Place,Seattle,Washington,98195,28
130,Mark,Jeffrey,Atkinson,13,67200.00,1979-02-04,2010-02-25,50,121,650.447.4686,94307 Annamark Junction,Seattle,Washington,98104,28
131,James,Ian,Marlow,13,60000.00,1984-06-21,2013-06-09,50,121,650.860.2883,1891 Sage Court,Seattle,Washington,98109,28
132,Gavin,Francis,Olson,13,52800.00,1973-02-16,2008-02-15,50,121,650.283.1659,9794 Carey Hill,Seattle,Washington,98109,28
133,Jason,Paul,Mallin,13,79200.00,1985-12-22,2016-12-06,50,122,650.315.4723,7975 Pleasure Crossing,Seattle,Washington,98166,28
134,Michael,Robert,Rogers,13,69600.00,1969-08-25,2018-08-22,50,122,650.763.3210,212 High Crossing Terrace,Seattle,Washington,98148,28
135,Mitch,Matthew,Holt,13,57600.00,1992-05-10,2012-05-23,50,122,650.500.8591,3 Muir Trail,Seattle,Washington,98104,28
136,Hazel,Danielle,Philtanker,13,52800.00,1994-10-17,2017-10-13,50,122,650.908.2415,8 South Avenue,Seattle,Washington,98185,28
137,Renske,NULL,Ladwig,13,86400.00,1972-07-18,2006-07-15,50,123,650.960.5034,8 Upham Crossing,Seattle,Washington,98127,28
138,Stephen,Curtis,Stiles,13,76800.00,1982-11-13,2018-11-09,50,123,650.538.5633,4403 Iowa Drive,Seattle,Washington,98127,28
139,Tony,Sean,Rogers,13,64800.00,1976-02-21,2017-02-12,50,123,650.250.0801,89 Randy Junction,Seattle,Washington,98109,28
140,Mayank,NULL,Patel,13,60000.00,1983-06-16,2010-06-05,50,123,650.281.1672,2954 North Plaza,Seattle,Washington,98104,28
141,Trenna,Jasmine,Rajs,13,84000.00,1965-09-27,2006-09-19,50,124,650.295.9197,6896 Reindahl Parkway,Seattle,Washington,98115,28
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28
144,Peter,Andrew,Vargas,13,60000.00,1975-05-24,2001-05-26,50,124,650.989.6665,764 Knutson Avenue,Seattle,Washington,98166,28

### **Second Challenge** 

Challenge: Select employees who live in any of the following cities: 

\- Seattle 

\- Sydney 

\- Ascot 

\- Hillston

In [3]:
SELECT * FROM hcm.employees 
WHERE city IN ('Seattle', 'Sydney', 'Ascot', 'Hillston');

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
100,Jack,John,Bernard,1,576000.00,1994-01-13,2017-01-23,90,NULL,515.996.5357,3 Kenwood Plaza,Seattle,Washington,98185,28
101,Don,Fred,Reilly,2,408000.00,1966-12-27,2006-12-28,90,100,515.848.4385,61 Banding Street,Seattle,Washington,98166,28
102,Judy,Georgia,Lawson,2,408000.00,1960-11-12,2010-11-26,90,100,515.195.9617,17 American Ash Trail,Seattle,Washington,98127,28
103,Yani,Michelle,Wenzlick,15,216000.00,1967-09-22,2002-09-06,60,102,590.117.7119,6 Pearson Junction,Seattle,Washington,98148,28
104,Rachel,Alison,Mortensen,15,144000.00,1959-07-27,2003-07-25,60,103,590.876.6936,27 Dunning Street,Seattle,Washington,98109,28
105,Paul,James,Cameron,15,115200.00,1985-12-20,2018-12-14,60,103,590.826.7764,3 Calypso Parkway,Seattle,Washington,98133,28
106,Russell,John,King,15,115200.00,1989-04-18,2008-04-21,60,103,590.964.4035,5 Barnett Drive,Seattle,Washington,98148,28
107,Maria,April,Cameron,15,100800.00,1973-03-11,2008-03-01,60,103,590.643.5171,578 Brentwood Parkway,Seattle,Washington,98140,28
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
110,John,NULL,Chen,5,196800.00,1961-01-24,2007-01-06,100,108,515.003.1575,406 Eastern road,Sydney,New South Wales,2481,2
111,Llyod,Eric,Henderson,5,184800.00,1992-10-02,2016-10-07,100,108,515.689.5566,60 Highway Road,Sydney,New South Wales,2155,2
112,Lena,Michelle,Chadwick,5,187200.00,1957-02-03,2004-02-04,100,108,515.390.5375,6 Argyle Rd,Sydney,New South Wales,2300,2
113,Richard,Mark,Stewart,5,165600.00,1967-10-20,2003-10-13,100,108,515.239.5085,16949 Harristown Rd,Sydney,New South Wales,2287,2
114,Diana,Mary,Colman,10,264000.00,1986-02-13,2013-02-20,30,100,515.776.5640,576 Nancy Alley,Seattle,Washington,98115,28
115,Alexander,NULL,Khoo,11,74400.00,1959-10-17,2011-10-04,30,114,515.125.0259,22270 Portage Park,Seattle,Washington,98104,28
116,Shelli,NULL,Baida,11,69600.00,1959-01-23,2016-01-10,30,114,515.513.4164,05 School Lane,Seattle,Washington,98121,28
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
119,Karen,Rhonda,Colmenares,11,60000.00,1987-03-06,2006-03-04,30,114,515.593.3752,23 Kennedy Drive,Seattle,Washington,98166,28
120,Matthew,Anthony,Wilson,12,196800.00,1970-10-13,2011-10-14,50,100,650.689.6900,91 Northland Plaza,Seattle,Washington,98127,28
121,Jack,Earl,Hale,12,196800.00,1966-09-13,2011-09-07,50,100,650.083.4633,3951 Merrick Lane,Seattle,Washington,98133,28
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
123,Shanta,NULL,Vollman,12,156000.00,1984-07-06,2002-07-09,50,100,650.878.7210,45623 Lyons Street,Seattle,Washington,98148,28
124,Kevin,NULL,Mourgos,12,139200.00,1970-09-03,2009-09-21,50,100,650.168.8824,52 Hollow Ridge Street,Seattle,Washington,98148,28
125,Julia,Aleisha,Nayer,13,76800.00,1972-09-16,2015-09-17,50,120,650.290.0080,7 Summerview Crossing,Seattle,Washington,98109,28
126,Irene,NULL,Mikkilineni,13,64800.00,1962-02-16,2001-02-22,50,120,650.810.3548,6 Veith Place,Seattle,Washington,98115,28
127,James,NULL,Landry,13,57600.00,1972-04-13,2011-04-11,50,120,650.816.0130,95 Elka Crossing,Seattle,Washington,98109,28
128,Steven,Andrew,Markle,13,52800.00,1970-08-19,2004-08-01,50,120,650.058.3953,18499 Autumn Leaf Trail,Seattle,Washington,98185,28
129,Laura,Tanya,Bissot,13,79200.00,1987-04-02,2016-04-08,50,121,650.824.8471,5378 Porter Place,Seattle,Washington,98195,28
130,Mark,Jeffrey,Atkinson,13,67200.00,1979-02-04,2010-02-25,50,121,650.447.4686,94307 Annamark Junction,Seattle,Washington,98104,28
131,James,Ian,Marlow,13,60000.00,1984-06-21,2013-06-09,50,121,650.860.2883,1891 Sage Court,Seattle,Washington,98109,28
132,Gavin,Francis,Olson,13,52800.00,1973-02-16,2008-02-15,50,121,650.283.1659,9794 Carey Hill,Seattle,Washington,98109,28
133,Jason,Paul,Mallin,13,79200.00,1985-12-22,2016-12-06,50,122,650.315.4723,7975 Pleasure Crossing,Seattle,Washington,98166,28
134,Michael,Robert,Rogers,13,69600.00,1969-08-25,2018-08-22,50,122,650.763.3210,212 High Crossing Terrace,Seattle,Washington,98148,28
135,Mitch,Matthew,Holt,13,57600.00,1992-05-10,2012-05-23,50,122,650.500.8591,3 Muir Trail,Seattle,Washington,98104,28
136,Hazel,Danielle,Philtanker,13,52800.00,1994-10-17,2017-10-13,50,122,650.908.2415,8 South Avenue,Seattle,Washington,98185,28
137,Renske,NULL,Ladwig,13,86400.00,1972-07-18,2006-07-15,50,123,650.960.5034,8 Upham Crossing,Seattle,Washington,98127,28
138,Stephen,Curtis,Stiles,13,76800.00,1982-11-13,2018-11-09,50,123,650.538.5633,4403 Iowa Drive,Seattle,Washington,98127,28
139,Tony,Sean,Rogers,13,64800.00,1976-02-21,2017-02-12,50,123,650.250.0801,89 Randy Junction,Seattle,Washington,98109,28
140,Mayank,NULL,Patel,13,60000.00,1983-06-16,2010-06-05,50,123,650.281.1672,2954 North Plaza,Seattle,Washington,98104,28
141,Trenna,Jasmine,Rajs,13,84000.00,1965-09-27,2006-09-19,50,124,650.295.9197,6896 Reindahl Parkway,Seattle,Washington,98115,28
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28
144,Peter,Andrew,Vargas,13,60000.00,1975-05-24,2001-05-26,50,124,650.989.6665,764 Knutson Avenue,Seattle,Washington,98166,28
190,Timothy,Mitchell,Gates,14,69600.00,1983-02-01,2018-02-08,NULL,122,650.340.2668,5 30w W #3083,Hillston,New South Wales,2675,2
199,Douglas,Robert,Grant,14,62400.00,1993-02-04,2016-02-25,NULL,124,650.742.9288,35673 Annapolis Rd #190,Ascot,Queensland,4359,2

### **Third Challenge** 

Challenge: Select employees from Sydney who have a salary greater than $200,000.

In [4]:
SELECT * FROM hcm.employees 
WHERE city = 'Sydney' AND salary > 200000;

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
108,Patricia,Dana,Doyle,4,288192.00,1971-08-14,2015-08-06,100,101,515.626.4805,286 Santa Rosa Ave,Sydney,New South Wales,1595,2
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2

### **Fourth Challenge** 

Challenge: Select employees who live in either Seattle or Sydney and were also hired on or after 1st January 2019.

In [5]:
SELECT * FROM hcm.employees 
WHERE city IN ('Seattle', 'Sydney') AND hire_date >= '2019-01-01';

employee_id,first_name,middle_name,last_name,job_id,salary,birth_date,hire_date,department_id,manager_id,phone,street_address,city,state_province,postal_code,country_id
109,Daniel,Alexander,Hopkins,5,216000.00,1995-04-15,2019-04-27,100,108,515.845.7923,8 Collins Ave,Sydney,New South Wales,2650,2
117,Peter,NULL,Owen,11,67200.00,1988-10-22,2019-10-12,30,114,515.114.7092,9506 Bultman Trail,Seattle,Washington,98115,28
118,Peter,Richard,Owen,11,62400.00,1994-02-23,2019-02-24,30,114,515.251.9362,503 Tennessee Crossing,Seattle,Washington,98140,28
122,Priya,NULL,Singh,12,189600.00,1980-08-04,2019-08-05,50,100,650.937.4754,750 Schmedeman Pass,Seattle,Washington,98195,28
142,Rick,David,Davies,13,74400.00,1977-04-13,2019-04-03,50,124,650.436.1986,08 Sutherland Lane,Seattle,Washington,98140,28
143,Randall,Patrick,Matos,13,62400.00,1957-05-24,2019-05-02,50,124,650.761.0990,42206 Elka Circle,Seattle,Washington,98148,28

### **Fifth Challenge** 

Challenge: Select products from the oes.products table which do not have a product category\_id of either 1, 2, or 5.

In [6]:
SELECT * FROM oes.products 
WHERE category_id NOT IN (1, 2, 5);

product_id,product_name,category_id,list_price,discontinued
7,Canon PIXMA MG2460 Inkjet MFP printer,7,39.0000,0
9,JKW Video Intercom over IP adaptor,6,495.0000,1
10,Intel Coffee Lake Core i9 Processor,8,779.0000,0
11,Horion 55 inch 4K Ultra HD LED TV,4,632.0000,0
12,Sony WH-1000XM3 Noise-Cancelling headphones - Black,4,459.0000,0
13,HyperX AMP 7.1 USB Sound Card,8,59.0000,0
14,HP LaserJet Pro M15W printer,7,23.2500,0
16,Canon EOS 3000D DSLR Entry-Level Camera,3,578.9900,0
17,MPS Intercom system,6,398.0000,1
18,Ugreen CM129 Audio Sound Card Adapter,8,28.7500,0
19,Nikon D3500 DSLR Camera,3,659.0000,0
20,GoPro HERO 8 Black Action Camera 4K Video,3,595.0000,0
21,DJI Mavic Mini Drone,3,623.5000,0
26,DJI Mavic 2 Pro Drone with Hasselblad Camera,3,2491.6700,0
27,Canon EF 50mm f/1.8 STM Lens for Canon Digital SLR Cameras,3,249.0000,0
28,Canon Black CLI-8 Ink Cartridge,7,32.0000,1
29,APY Intercom System,6,350.0000,1
30,Leadtek Quadro P620 Professional Workstation Graphics Card,8,349.9400,0
31,Logitech Z333 2.1 Multimedia Speaker System,4,159.0000,0
32,Blue Yeti Microphone,4,258.9900,0
33,Edifier Multimedia 2.0 system PC Speaker,4,22.9400,0
36,Leadtek Quadro P1000 Full Performance Professional Graphics Card,8,688.8500,0
37,Leadtek Quadro P400 Professional Workstation Graphics Card,8,240.3500,0
40,Samsung 1TB Solid State Drive SSD,8,194.3500,0
41,Crucial MX500 500GB SSD,8,132.2500,0
45,Aten UC3020 CamLive HDMI to USB-C Video Capture,8,251.0000,0
46,Cooler Master Hyper 212,8,74.7500,0
47,Canon EOS M50 Mirrorless Camera,3,989.0000,0
48,Canon EOS 80D DSLR Camera Single Lens Kit,3,1499.0000,0
49,GoPro HERO 7 Silver Action Camera 4K Video,3,325.6200,0
50,Comet Drone with Camera,3,99.0000,0
51,HP Ink Cartridge 65XL Black,7,44.4900,0
53,AB Security cam,6,300.0000,1
54,Panasonic VL-SWD272 Wireless Video Intercom System,6,661.2500,0
55,RING Smart Video Wi-Fi Doorbell 3,6,398.9900,0
58,Cooler Master MasterFan,8,98.9900,0
59,Samsung 50TU8000 50 inch 4K Smart TV,4,1426.0000,0
60,Konic 55 inch 4K Ultra HD LED TV,4,747.5000,0
62,Viper-X Drone with VR Headset,3,69.9900,0
68,Andromeda Drone with Camera,3,49.9900,0
69,PowerBeats Pro True Wireless Sports Earphones,4,332.9900,0
71,Apple AirPods Pro Noise Cancelling True Wireless Headphones,4,409.0000,0
72,Sennheiser HD 4.30i Over-Ear Headphones,4,98.9900,0
73,Corsair LL Series LL120 Fan,8,192.9900,0
74,Canon Ink Cartridge PG645,7,33.8200,0
78,PBX Noise Cancelling Headphones,4,80.0000,0